##
# CONFIGURATION TEMPLATE
#
# rename this file in config.yaml
# set commented parameters
# uncomment and set desired sections
##

vm:
  hostname: # set hostname
  network:
    type: # set networking type 'forwarded_port' | 'private_network'

#    PRIVATE NETWORK PARAMETERS
#    ip: 192.168.50.4

#    FORWARDED PORT LIST
#    ports:
#      - { guest: 80, host: 8080, auto_correct: true }

